version: '3.7'
services:
  db:
    image: postgres:14.2-alpine
    ports:
      - 5400:5432
    volumes:
      - ./docker/postgres/init.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: postgres
    hostname: postgres
    restart: always
    user: root

volumes:
  postgres_data:
